language: android
java: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-google-google_play_services  - extra-google-m2repository
    - extra-android-m2repository
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
stages:
  - name: test
    if: NOT(branch = development)
  - name: deploy
    if: tag IS present
jobs:
  include:
    - stage: test
      script: "./gradlew test"
    - stage: deploy
      script: "./gradlew assembleRelease"
      deploy:
        provider: releases
        api_key:
          secure: iueF0FXj8IoWlDBfbv+O/3iPAFDX+RIIUvPcHuW4PPphOp71LKGZNUxfjRdfO7WQsYpRfhxT55lxp9TeU4gcPegL/WKHMER82DwfPPYM0wFFZfWvZ6bC6yTSN9fT7kkCFc2UAHAtjI9iteYvM5vcduvqfUeb89kYvOIgVkoUB21ykAE+S/bTwmC9rdgdOfsMYrenRGx1VcIbmVmcKEhWb2KaG4mOwRIwzgbbgLMRMX/tC6Kqjy9HATKbKbV+2hRPeZdIbfx/cUpQN/fAX1TU1O9/xPChkr6YDRmJleZsKKzng9IXhD2H5OlYnD2oGQAFWU20o1cO+g/aWW6gu1Kpq/lzf8mtLtNYBmcOY7ufmcBHlaMv/HeQ/kQ9ZSohaB6k4R7C/Whc0+3wZ0ir0XEzCwEBL3XbmTRCyroJAWLfpOUDbFowXSg0cH3OyLUfTYC6QHgw8xVLUrCVJ0Bx1C+E3VmiKEeQnuy3uYB3WFWRzGKZQ1TT8NhyKLz/Cx3TkIWCe6/Q/yEJC6u1V4Bhu+M07nVZfgLzQKx7/WliAqudTxS08oaWH56rG21SzzcRG/1YEUgrD4qjkLeCFmNjjB4zodka6LgXy0wvrGrwAiVFVnH3KSVNht0Jj+AhUGG0hIfxFQut/Zsuxv3h7RJmNcpAamac87mtpFbwqq4FX0CiaMI=
        file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/app-release.apk
        skip_cleanup: true
        overwrite: true
        on:
          tags: true

before_install:
  - openssl aes-256-cbc -K $encrypted_cdc0677920ab_key -iv $encrypted_cdc0677920ab_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
  - tar xzvf secrets.tar.gz
  - chmod +x gradlew
  - export TZ=America/Santiago
notifications:
  slack:
    secure: H2hZzWsFuQYi71yLf/BXUAfAh8wtoQ2+3nMxV/nS/co8Tdb1XNMHBI5Ed5VdWl8bPMUhp+XHLH0zm3QsrcQrndD0pqqRPmoPo/kBpj/BIebfwIB8yhL7vsAWaEQU1/vTsPv+FD3J0yPa7mrzgRB1fNs7JNawL9TBtX+PKY7IbwtG+79e6Mqyp3D74n+EpQIQ3MlUxWFyZ6//PK7EdQwEWrC0h+AXVbq8BY6oXgRQ4tXgRbkHxCukJCcWju1yY1Uka9gnSRnpbr2lWHqO/AkFTwCf4PDhwIdQnoYzawcAbpePAzJz0ArvvJGZWaLLKk+X5mQtVwDPVhqRiqnhSgDS3ZUDzv5P6lT3rE1MHke+8XxS5RL7QR/i9JI29IZ15ldTAzqKh2yhHr1gaxoJvpmdspmM7RIbl4Ue3XSDUgo55+U/EX+MYjHy+29Eg7cZdmcXe/aEw6uz/HyYjh9VX+9bljq2l2KRirpKAxiwNMWSpEBfSpgctTluWJsJk/cv68zTK2VysXj3jRKjUvnoWy3AH9CUcQ4fyk9LUMWBtVIrHV20H71SwlxC9cVFnB0KoMYrFqhJNgAA1a8e6QW7cyrK0vd73DNZ5vqKXIT2JWIY7B3wAoqRLD1DzKUwAYBsz+kBGEt7pngqK0XlcQBvsW6Wg0BJF7TvXEXJD6sQ1EHt0AE=