language: android
java: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-google-google_play_services  - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_cdc0677920ab_key -iv $encrypted_cdc0677920ab_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
  - tar xzvf secrets.tar.gz
  - chmod +x gradlew
  - export TZ=America/Santiago
script:
  - "./gradlew clean"
  - "./gradlew assemble"
  - "./gradlew test"
notifications:
  slack:
    secure: H2hZzWsFuQYi71yLf/BXUAfAh8wtoQ2+3nMxV/nS/co8Tdb1XNMHBI5Ed5VdWl8bPMUhp+XHLH0zm3QsrcQrndD0pqqRPmoPo/kBpj/BIebfwIB8yhL7vsAWaEQU1/vTsPv+FD3J0yPa7mrzgRB1fNs7JNawL9TBtX+PKY7IbwtG+79e6Mqyp3D74n+EpQIQ3MlUxWFyZ6//PK7EdQwEWrC0h+AXVbq8BY6oXgRQ4tXgRbkHxCukJCcWju1yY1Uka9gnSRnpbr2lWHqO/AkFTwCf4PDhwIdQnoYzawcAbpePAzJz0ArvvJGZWaLLKk+X5mQtVwDPVhqRiqnhSgDS3ZUDzv5P6lT3rE1MHke+8XxS5RL7QR/i9JI29IZ15ldTAzqKh2yhHr1gaxoJvpmdspmM7RIbl4Ue3XSDUgo55+U/EX+MYjHy+29Eg7cZdmcXe/aEw6uz/HyYjh9VX+9bljq2l2KRirpKAxiwNMWSpEBfSpgctTluWJsJk/cv68zTK2VysXj3jRKjUvnoWy3AH9CUcQ4fyk9LUMWBtVIrHV20H71SwlxC9cVFnB0KoMYrFqhJNgAA1a8e6QW7cyrK0vd73DNZ5vqKXIT2JWIY7B3wAoqRLD1DzKUwAYBsz+kBGEt7pngqK0XlcQBvsW6Wg0BJF7TvXEXJD6sQ1EHt0AE=